### ISSUE TITLE
Consider providing a uefi-run library

### ISSUE THREAD

**Issue by nicholasbishop** [Richard-W/uefi-run#13]
It would be nice to be able to re-use this code as a library. For example, a project that builds a UEFI app might have a test harness that runs the app in qemu. If that test code is a shell script or perhaps a github actions yaml file then just installing uefi-run and running it is convenient enough, but a more complicated test harness could itself be written in Rust, and then it would be nice to directly call uefi-run as a library.

I have a PR that takes a first pass at implementing this, but since I don't know if that approach is desirable (or if librarification is something you are interested in in the first place) I figured an accompanying issue would be good to make.

**Comment by richard-w** [comment]
Sorry for the long response time. I don't have a lot of free time right now.

I like the idea but I am not sure if this should be within the scope of this project. uefi-run pretty much just uses the `fatfs` crate to create an image and calls qemu.

I will play around with the idea a bit a soon as I find time. It's nice that you already wrote the PR but I do have some problems with the structure of how you did things. I will leave it open until I have explored the problem space a bit more and give informed feedback. It's somewhat likely that I will create a competing PR though. I hope you're okay with that.

**Comment by nicholasbishop** [comment]
Yep no problem! Thanks for looking into it this.

**Comment by richard-w** [comment]
@nicholasbishop Please check whether PR #18 solves your problem.

**Comment by richard-w** [comment]
PR #18 adds a library target. This will land on crates.io with version 0.5.0. In the meantime projects needing this target can use the dependency line `uefi-run = { git = "https://github.com/Richard-W/uefi-run" }`.

**Comment by nicholasbishop** [comment]
Sorry I missed your earlier question -- looks great, thank you!
