### ISSUE TITLE
Custom startup.nsh

### ISSUE THREAD

**Issue by stevefan1999-personal** [Richard-W/uefi-run#22]
I want to bypass the 5 seconds boot delay but seems like startup.nsh is hardcoded here

https://github.com/Richard-W/uefi-run/blob/ce8aa1462d82e2cc24d66e05a03a8bdb55765746/src/main.rs#L47-L49

**Comment by richard-w** [comment]
You should be able to override the default startup.nsh using the `--add-file` argument. Something like `uefi-run --add-file your-custom-script.nsh:startup.nsh /path/to/your/image` should work for you.

**Comment by stevefan1999-personal** [comment]
Yes! Unfortunately, setting `set StartupDelay 0` doesn't work. Closing this as solved. Better have a discussion section next time.

**Comment by Tim-Paik** [comment]
I think I solved this in #23 !
