### ISSUE TITLE
AArch64 support?

### ISSUE THREAD

**Issue by RaitoBezarius** [Richard-W/uefi-run#26]
It'd be awesome if `uefi-run` supported other architectures and notably AArch64 or RISCV64. :)

Actually, I notice the `--qemu-flag`, which can enable other architectures.

**Comment by samueldr** [comment]
The `--boot` argument is hardcoded to `bootx64.efi`

https://github.com/Richard-W/uefi-run/blob/7cd45d1a5a08a47987afb6a322455cee1be07ae1/src/main.rs#L42-L45

So it will need some more *smarts* in it.

As a workaround, `--add-file` can be used.

```
--add-file "target/${RUST_TARGET}/debug/uefi-hello-world.efi:EFI/Boot/BootAA64.efi"
```
